import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';
import FastfoodIcon from '@mui/icons-material/Fastfood';
import HomeIcon from '@mui/icons-material/Home';
import DeveloperModeIcon from '@mui/icons-material/DeveloperMode';
import bcrypt from 'bcryptjs';
import { Image } from '@nextui-org/react';

export const socialData = [
  {
    name: 'Shopee',
    image: '/static/social/shopee.webp',
    link: 'https://shp.ee/gwha2zv',
  },
  {
    name: 'Tiktok',
    image: '/static/social/tiktok.webp',
    link: 'https://www.tiktok.com/@smartbuysphilippines',
  },
  {
    name: 'Instagram',
    image: '/static/social/instagram.webp',
    link: 'https://www.instagram.com/smartbuysphilippines/',
  },
  {
    name: 'Facebook',
    image: '/static/social/efbee.webp',
    link: 'https://www.facebook.com/smartbuysphil',
  },
];

export const weDoProductList = [
  {
    name: 'clothes',
    description: 'SmartBuys Philippines Wholesale Clothes Supplier',
    width: '70%',
    height: '100%',
    color: 'lime',
    image: '/static/clothes_web.webp',
    contentTitle: 'Wholesale and Retails Prices are available',
    contentDetails:
      'All SM Department Store display brands include HUMAN, MCBETH, TEE, and BENCH (Brand new mall pull outs, bodega sale, and direct from manufacturer, respectively)',
    icon: (
      <ShoppingCartIcon
        style={{ color: 'Lime', fontSize: '4rem', marginTop: '1.8rem' }}
      />
    ),
  },
  {
    name: 'food',
    description: 'SmartBuys Philippines Frozen Food Products',
    width: '70%',
    height: '100%',
    color: 'red',
    image: '/static/food_web.webp',
    contentTitle: 'Frozen Food Official Distributor and Supplier',
    contentDetails:
      'Zingy Bites, KingBites and SnackOn are open for distributors, resellers, and retailers',
    icon: (
      <FastfoodIcon
        style={{ color: 'Red', fontSize: '4rem', marginTop: '1.7rem' }}
      />
    ),
  },
  {
    name: 'home',
    description: 'SmartBuys Philippines Home Essential Products',
    width: '70%',
    height: '100%',
    color: 'gold',
    image: '/static/home.webp',
    contentTitle: 'Home Essential Official Distributor',
    contentDetails:
      'SmartBuys Philippines is an official distributor of well-known local and international brands, available everyday, all year round! in addition to kitchenware, cookware, baking needs, home appliances, bedroom essentials, bathroom essentials, and more, we also offer a wide variety of other products!',
    icon: (
      <HomeIcon
        style={{
          color: 'Gold',
          fontSize: '4rem',
          marginTop: '1.7rem',
        }}
      />
    ),
  },
  {
    name: 'tech',
    description: 'SmartBuys Philippines Digital Content',
    width: '70%',
    height: '100%',
    color: 'blue',
    image: '/static/tech_web.webp',
    contentTitle: 'Web and Mobile Application Development',
    contentDetails:
      'We offer a variety of services, including Enterprise Application Development, Website Development, Mobile Application Development (for Android and iOS), Cloud Services, Custom Domains, SEO and much more!',
    icon: (
      <DeveloperModeIcon
        style={{
          color: 'Blue',
          fontSize: '4rem',
          marginTop: '1.7rem',
        }}
      />
    ),
  },
];

export const weAreProductList = [
  {
    name: 'foody',
    description: 'Foody',
    width: '70%',
    height: '100%',
    image: '/static/foody.webp',
  },
  {
    name: 'kingbites',
    description: 'KingBites ',
    width: '100%',
    height: '100%',
    image: '/static/kb.webp',
  },
  {
    name: 'horus',
    description: 'Horus Tech',
    width: '90%',
    height: '100%',
    image: '/static/horus_tech.webp',
  },
  {
    name: 'casey_lucas',
    description: 'Casey & Lucas',
    width: '90%',
    height: '100%',
    image: '/static/casey_lucas.webp',
  },
  {
    name: 'happy_app',
    description: 'Happy App',
    width: '45%',
    height: '100%',
    image: '/static/happy_app.webp',
  },
];

export const reviewList = [
  {
    name: 'shop_rating_1',
    image: '/static/shop_review/shop_rating_1.webp',
  },
  {
    name: 'shop_rating_2',
    image: '/static/shop_review/shop_rating_2.webp',
  },
  {
    name: 'shop_rating_3',
    image: '/static/shop_review/shop_rating_3.webp',
  },
  {
    name: 'shop_rating_4',
    image: '/static/shop_review/shop_rating_4.webp',
  },
  {
    name: 'shop_rating_5',
    image: '/static/shop_review/shop_rating_5.webp',
  },
  {
    name: 'shop_rating_6',
    image: '/static/shop_review/shop_rating_6.webp',
  },
  {
    name: 'shop_rating_7',
    image: '/static/shop_review/shop_rating_7.webp',
  },
  {
    name: 'shop_rating_8',
    image: '/static/shop_review/shop_rating_8.webp',
  },
];

export const userSeed = {
  users: [
    {
      name: 'SmartBuys Philippines',
      email: process.env.SUPER_ROOT_USERNAME,
      password: bcrypt.hashSync(process.env.SUPER_ROOT_PASSWORD || ''),
      isAdmin: true,
    },
    {
      name: 'SmartBuys Philippines Admin',
      email: process.env.SUPER_ADMIN_USERNAME,
      password: bcrypt.hashSync(process.env.SUPER_ADMIN_PASSWORD || ''),
      isAdmin: false,
    },
  ],
};

export const productSeed = {
  products: [
    {
      name: 'Disney Elsa Anna',
      price: 189,
      description: 'Disney Elsa Anna Frozen',
      image: '',
      category: 'Girls',
      type: 'Terno',
    },
  ],
};

export const appCostCalculator = [
  {
    image: (
      <Image
        showSkeleton
        src="/static/devices/android.webp"
        width="50%"
        height="100%"
        objectFit="contain"
        alt="SmartBuys Philippines Android App"
      />
    ),
  },
  {
    image: (
      <Image
        showSkeleton
        src="/static/devices/mac.webp"
        width="100%"
        height="100%"
        objectFit="contain"
        alt="SmartBuys Philippines Desktop App"
      />
    ),
  },
  {
    image: (
      <Image
        showSkeleton
        src="/static/devices/ios.webp"
        width="50%"
        height="100%"
        objectFit="contain"
        alt="SmartBuys Philippines iOS"
      />
    ),
  },
];

const ternoPrice = 210;
const joggerPrice = 250;
const dressPrice = 210;
const shortsPrice = 220;
const shirtPrice = 250;
const sandoPrice = 230;

export const productList = [
  {
    _id: 1,
    name: 'Disney Elsa Anna',
    description: 'Disney Elsa Anna Frozen',
    price: ternoPrice,
    image: '/static/shop/disney/D1.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 2,
    name: 'Disney Believe',
    description: 'Disney Paw Patrol Believe',
    price: ternoPrice,
    image: '/static/shop/disney/D2.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 3,
    name: 'Disney Happy',
    description: 'Disney Happy Together',
    price: ternoPrice,
    image: '/static/shop/disney/D3.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 4,
    name: 'Disney Unicorn',
    description: 'Disney Minnie Unicorn Rainbow',
    price: ternoPrice,
    image: '/static/shop/disney/D4.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 5,
    name: 'Pony Unicorn',
    description: 'My Little Pony Unicorn',
    price: ternoPrice,
    image: '/static/shop/disney/D5.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 6,
    name: 'Barbie Unicorn',
    description: 'Disney Princess Barbie Unicorn',
    price: ternoPrice,
    image: '/static/shop/disney/D7.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 7,
    name: 'Barbie Heart',
    description: 'Barbie Heart',
    price: ternoPrice,
    image: '/static/shop/disney/D8.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 8,
    name: 'Unicorn Magic',
    description: 'Disney Unicorn Magic',
    price: ternoPrice,
    image: '/static/shop/disney/D9.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 9,
    name: 'Disney Belle',
    description: 'Disney Princess Belle',
    price: ternoPrice,
    image: '/static/shop/disney/D10.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 10,
    name: 'Disney Minnie',
    description: 'Disney Minnie',
    price: ternoPrice,
    image: '/static/shop/disney/D11.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 11,
    name: 'Disney Little Mermaid',
    description: 'My Little Mermaid',
    price: ternoPrice,
    image: '/static/shop/disney/D12.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 12,
    name: 'Disney Minnie',
    description: 'Disney Minnie Mouse',
    price: ternoPrice,
    image: '/static/shop/disney/D13.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 13,
    name: 'Disney Minnie',
    description: 'Disney Minnie Mouse Two Hearts',
    price: ternoPrice,
    image: '/static/shop/disney/D14.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 14,
    name: 'Disney Belle',
    description: 'Disney Belle So Magical',
    price: ternoPrice,
    image: '/static/shop/disney/D15.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 15,
    name: 'Disney Barbie',
    description: 'Disney Barbie Happiness',
    price: ternoPrice,
    image: '/static/shop/disney/D16.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 16,
    name: 'Hello Kittye',
    description: 'Helly Kitty Sanrio',
    price: ternoPrice,
    image: '/static/shop/disney/D17.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 17,
    name: 'Paw Patrol Sky',
    description: 'Paw Patrol Sky',
    price: ternoPrice,
    image: '/static/shop/disney/D19.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 18,
    name: 'Disney Minnie',
    description: 'Disney Minnie Mouse Pink',
    price: ternoPrice,
    image: '/static/shop/disney/D20.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 19,
    name: 'Disney Barbie',
    description: 'Disney Barbie Pink',
    price: ternoPrice,
    image: '/static/shop/disney/D21.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 20,
    name: 'Disney Elsa',
    description: 'Disney Elsa Yellow',
    price: ternoPrice,
    image: '/static/shop/disney/D25.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 21,
    name: 'Disney Elsa',
    description: 'Disney Elsa Frozen',
    price: ternoPrice,
    image: '/static/shop/disney/D26.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 22,
    name: 'My Little Pony',
    description: 'My Little Pony Friendships are Magical',
    price: ternoPrice,
    image: '/static/shop/disney/D27.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 23,
    name: 'Paw Patrol Skye',
    description: 'Paw Patrol Sky High Flying Skye',
    price: ternoPrice,
    image: '/static/shop/disney/D28.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 24,
    name: 'Paw Patrol Skye',
    description: 'Paw Patrol Sky Believe',
    price: ternoPrice,
    image: '/static/shop/disney/D29.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 25,
    name: 'Disney Minnie Mouse',
    description: 'Disney Minnie Mouse Unicorn',
    price: ternoPrice,
    image: '/static/shop/disney/D30.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 26,
    name: 'Disney Minnie Mouse',
    description: 'Disney Minnie Mouse Red',
    price: ternoPrice,
    image: '/static/shop/disney/D31.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 27,
    name: 'Disney Unicorn',
    description: 'Disney Unicorn You Are Magical',
    price: ternoPrice,
    image: '/static/shop/disney/D34.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 28,
    name: 'Disney Mickey Gang',
    description: 'Disney Mickey Gang Happy Together',
    price: ternoPrice,
    image: '/static/shop/disney/D36.webp',
    category: 'Girls',
    type: 'Terno',
  },
  {
    _id: 29,
    name: 'Hello Kitty Red',
    description: 'Hello Kitty Red',
    price: dressPrice,
    image: '/static/shop/dress/DS1.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 30,
    name: 'Disney Little Mermaid',
    description: 'Disney My Little Mermaid',
    price: dressPrice,
    image: '/static/shop/dress/DS2.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 31,
    name: 'Disney Barbie',
    description: 'Disney Barbie Purple',
    price: dressPrice,
    image: '/static/shop/dress/DS3.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 32,
    name: 'Disney Barbie',
    description: 'Disney Barbie Beauty',
    price: dressPrice,
    image: '/static/shop/dress/DS4.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 33,
    name: 'My Little Pony',
    description: 'Disney My Little Pony',
    price: dressPrice,
    image: '/static/shop/dress/DS5.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 34,
    name: 'Disney Minnie Mouse',
    description: 'Disney Minnie Mouse Bow',
    price: dressPrice,
    image: '/static/shop/dress/DS6.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 35,
    name: 'LOL',
    description: 'LOL',
    price: dressPrice,
    image: '/static/shop/dress/DS7.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 36,
    name: 'Disney My Little Pony',
    description: 'Disney My Little Pony Purple',
    price: dressPrice,
    image: '/static/shop/dress/DS8.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 37,
    name: 'Disney Minnie Mouse',
    description: 'Disney Minnie Mouse Red',
    price: dressPrice,
    image: '/static/shop/dress/DS9.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 38,
    name: 'Disney Minnie Mouse',
    description: 'Disney Minnie Mouse Blue Greem',
    price: dressPrice,
    image: '/static/shop/dress/DS11.webp',
    category: 'Girls',
    type: 'Dress',
  },
  {
    _id: 39,
    name: 'Jordan Sando',
    description: 'Jordan Rise Above All',
    price: sandoPrice,
    image: '/static/shop/jordan/J1.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 40,
    name: 'Jordan 23 Sando',
    description: 'Jordan 23 Sando Black',
    price: sandoPrice,
    image: '/static/shop/jordan/J2.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 41,
    name: 'Jordan Rise Above All',
    description: 'Jordan Rise Above All Yellow',
    price: sandoPrice,
    image: '/static/shop/jordan/J3.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 42,
    name: 'Micheal Jordan 23',
    description: 'Michael Jordan 23 Sando',
    price: sandoPrice,
    image: '/static/shop/jordan/J4.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 43,
    name: 'Jordan Flight',
    description: 'Jordan Flight Sando Black',
    price: sandoPrice,
    image: '/static/shop/jordan/J5.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 44,
    name: 'Jordan 23',
    description: 'Jordan 23 Yellow',
    price: sandoPrice,
    image: '/static/shop/jordan/J6.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 45,
    name: 'Nike Check',
    description: 'Nike Check Comoflouge',
    price: sandoPrice,
    image: '/static/shop/jordan/J7.webp',
    category: 'Boys',
    type: 'Sando',
  },
  {
    _id: 46,
    name: 'Nike Athletic Department',
    description: 'Nike Athletic Department Blue Shirt',
    price: shirtPrice,
    image: '/static/shop/jordan/J8.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 47,
    name: 'Michael Jordan Blue',
    description: 'Michael Jordan Blue',
    price: shirtPrice,
    image: '/static/shop/jordan/J9.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 48,
    name: 'Jordan Hard Times',
    description: 'Jordan Hard Times Good Times',
    price: shirtPrice,
    image: '/static/shop/jordan/J10.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 49,
    name: 'Nike Check',
    description: 'Nike Check Blue',
    price: shirtPrice,
    image: '/static/shop/jordan/J11.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 50,
    name: 'Nike Check',
    description: 'Nike Check Black',
    price: shirtPrice,
    image: '/static/shop/jordan/J12.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 51,
    name: 'Nike Legend',
    description: 'Nike The Legend Lives On',
    price: shirtPrice,
    image: '/static/shop/jordan/J13.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 52,
    name: 'Nike Bred Up',
    description: 'Nike Get Your Bred Up',
    price: shirtPrice,
    image: '/static/shop/jordan/J14.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 53,
    name: 'Nike Jordan',
    description: 'Nike Jordan',
    price: shirtPrice,
    image: '/static/shop/jordan/J15.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 54,
    name: 'Nike Just Do It',
    description: 'Nike Just Do It',
    price: shirtPrice,
    image: '/static/shop/jordan/J16.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 55,
    name: 'Nike Just Do It',
    description: 'Nike Just Do It Check Orange',
    price: shirtPrice,
    image: '/static/shop/jordan/J17.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 56,
    name: 'Nike Air Jordan',
    description: 'Nike Air Jordan',
    price: shirtPrice,
    image: '/static/shop/jordan/J19.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 57,
    name: 'Nike Air Jordan',
    description: 'Nike Air Michael Jordan',
    price: shirtPrice,
    image: '/static/shop/jordan/J30.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 58,
    name: 'Nike Air Jordan',
    description: 'Nike Air Michael Jordan Brand Of Flight',
    price: shirtPrice,
    image: '/static/shop/jordan/J31.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 59,
    name: 'Nike Check',
    description: 'Nike Check',
    price: shirtPrice,
    image: '/static/shop/jordan/J36.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 60,
    name: 'Nike Michael Jordan 23',
    description: 'Nike Michael Jordan 23',
    price: shirtPrice,
    image: '/static/shop/jordan/J39.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 61,
    name: 'Nike One More Pair',
    description: 'Nike Just One More Pair',
    price: shirtPrice,
    image: '/static/shop/jordan/J40.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 62,
    name: 'Nike Rise',
    description: 'Nike Rise Above All',
    price: shirtPrice,
    image: '/static/shop/jordan/J41.webp',
    category: 'Boys',
    type: 'Shirt',
  },
  {
    _id: 63,
    name: 'Nike Jordan',
    description: 'Nike Jordan Shorts Yellow',
    price: shortsPrice,
    image: '/static/shop/shorts/S1.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 64,
    name: 'Nike Jordan',
    description: 'Nike Jordan Shorts Green',
    price: shortsPrice,
    image: '/static/shop/shorts/S2.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 65,
    name: 'Just Do It',
    description: 'Just Do It Grey',
    price: shortsPrice,
    image: '/static/shop/shorts/S3.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 66,
    name: 'Nike Shorts',
    description: 'Nike Shorts White',
    price: shortsPrice,
    image: '/static/shop/shorts/S4.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 67,
    name: 'Nike Shorts',
    description: 'Nike Shorts Orange',
    price: shortsPrice,
    image: '/static/shop/shorts/S5.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 68,
    name: 'Nike Jordan',
    description: 'Nike Jordan Blue',
    price: shortsPrice,
    image: '/static/shop/shorts/S6.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 69,
    name: 'Nike Jump Man',
    description: 'Nike Jordan Jump Man Yellow',
    price: shortsPrice,
    image: '/static/shop/shorts/S7.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 70,
    name: 'Nike Air Jordan',
    description: 'Nike Air Jordan Blue',
    price: shortsPrice,
    image: '/static/shop/shorts/S8.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 71,
    name: 'Nike Jordan',
    description: 'Nike Jordan Blue',
    price: shortsPrice,
    image: '/static/shop/shorts/S9.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 72,
    name: 'Nike Jordan',
    description: 'Nike Jordan Black',
    price: shortsPrice,
    image: '/static/shop/shorts/S10.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 73,
    name: 'Jordan 23',
    description: 'Jordan 23 Yellow',
    price: shortsPrice,
    image: '/static/shop/shorts/S11.webp',
    category: 'Boys',
    type: 'Shorts',
  },
  {
    _id: 74,
    name: 'Jordan Jogger',
    description: 'Jordan Jogger Grey',
    price: joggerPrice,
    image: '/static/shop/jogger/JG1.webp',
    category: 'Boys',
    type: 'Jogger',
  },
  {
    _id: 75,
    name: 'Jordan Jogger',
    description: 'Jordan Jogger Yellow',
    price: joggerPrice,
    image: '/static/shop/jogger/JG2.webp',
    category: 'Boys',
    type: 'Jogger',
  },
  {
    _id: 76,
    name: 'Jordan Jogger',
    description: 'Jordan Jogger Black',
    price: joggerPrice,
    image: '/static/shop/jogger/JG3.webp',
    category: 'Boys',
    type: 'Jogger',
  },
  {
    _id: 77,
    name: 'Chicken Nuggets',
    description: 'Famous Original Chicken Nuggets',
    price: 180,
    image: '/static/shop/food/nuggets.webp',
    category: 'Food',
    type: 'Food',
  },
  {
    _id: 78,
    name: 'Potato Fries',
    description: 'Original Potato Fries',
    price: 110,
    image: '/static/shop/food/fries.webp',
    category: 'Food',
    type: 'Food',
  },
  {
    _id: 79,
    name: 'Famous Crispy Bacon',
    description: 'Famous Original Crispy Bacon',
    price: 210,
    image: '/static/shop/food/bacon.webp',
    category: 'Food',
    type: 'Food',
  },
  {
    _id: 80,
    name: 'Famous Siomai',
    description: 'Famous Authentic Siomai',
    price: 190,
    image: '/static/shop/food/siomai.webp',
    category: 'Food',
    type: 'Food',
  },
  {
    _id: 81,
    name: 'Famous Longganisa',
    description: 'Famous Authentic Skinless Longganisa',
    price: 100,
    image: '/static/shop/food/longganisa.webp',
    category: 'Food',
    type: 'Food',
  },
];
